
server:
  port: 9000
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mariadb://${DATABASE_IP}:${DATABASE_PORT}/${DATABASE_NAME}?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        globally_quoted_identifiers: true
    show-sql: true

decorator:
  datasource:
    p6spy:
      enable-logging: true

